name: CI

on:
  push:
  pull_request:
    branches: [ $default-branch ]
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  ubuntu:
    name: "Ubuntu"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: [23, 24, 25]
    container:
      image: erlang:${{ matrix.otp }}
    steps:
    - uses: actions/checkout@v3
    - name: Format check
      run: rebar3 format --verify
    - name: Tests
      run: rebar3 test
