name: Publish to hex.pm

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    name: "Ubuntu"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: [25]
    container:
      image: erlang:${{ matrix.otp }}
    steps:
    - uses: actions/checkout@v3
    - name: Publish to Hex.pm
      env:
        HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
      run: |
           rebar3 edoc
           rebar3 hex publish -r hexpm --yes
